name: ESO Macos Build

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout this project
        uses: actions/checkout@v2
        with:
          path: actions

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      - name: Flutter SDK install
        run: |
          git clone https://github.com/flutter/flutter.git --depth=1 -b 1.20.0 _flutter
          echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"

      - name: Flutter set
        run: |
          flutter --version
          flutter config --enable-macos-desktop

      - name: Checkout flutter project
        uses: actions/checkout@v2
        with:
          repository: mabDc/eso_from_gitlab
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}
          path: eso

      - name: Build macos
        run: |
          cd eso
          flutter pub get
          flutter build macos -v

      - name: Upload flutter macos
        uses: actions/upload-artifact@v2
        with:
          name: ESO_MACOS
          path: eso/build/macos/Build/Products/Release/*.app/
          if-no-files-found: error
